// Generated by tool/ffigen.dart from the vendored llama.cpp
// headers (third_party/llama.cpp). Do not edit by hand.
// ignore_for_file: type=lint
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import, unused_element, deprecated_member_use_from_same_package
@ffi.DefaultAsset('package:myapps_ai_llm_llama/llama')
library;

import 'dart:ffi' as ffi;

@ffi.Native<ffi.Void Function()>()
external void llama_backend_init();

@ffi.Native<llama_batch Function(ffi.Pointer<ffi.Int32>, ffi.Int32)>()
external llama_batch llama_batch_get_one(
  ffi.Pointer<ffi.Int32> tokens,
  int n_tokens,
);

/// Apply chat template. Inspired by hf apply_chat_template() on python.
///
/// NOTE: This function does not use a jinja parser. It only support a pre-defined list of template. See more: https://github.com/ggml-org/llama.cpp/wiki/Templates-supported-by-llama_chat_apply_template
/// @param tmpl A Jinja template to use for this chat.
/// @param chat Pointer to a list of multiple llama_chat_message
/// @param n_msg Number of llama_chat_message in this chat
/// @param add_ass Whether to end the prompt with the token(s) that indicate the start of an assistant message.
/// @param buf A buffer to hold the output formatted prompt. The recommended alloc size is 2 * (total number of characters of all messages)
/// @param length The size of the allocated buffer
/// @return The total number of bytes of the formatted prompt. If is it larger than the size of buffer, you may need to re-alloc it and then re-apply the template.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<llama_chat_message>,
    ffi.Size,
    ffi.Bool,
    ffi.Pointer<ffi.Char>,
    ffi.Int32,
  )
>()
external int llama_chat_apply_template(
  ffi.Pointer<ffi.Char> tmpl,
  ffi.Pointer<llama_chat_message> chat,
  int n_msg,
  bool add_ass,
  ffi.Pointer<ffi.Char> buf,
  int length,
);

@ffi.Native<llama_context_params Function()>()
external llama_context_params llama_context_default_params();

@ffi.Native<ffi.Int32 Function(ffi.Pointer<llama_context>, llama_batch)>()
external int llama_decode(ffi.Pointer<llama_context> ctx, llama_batch batch);

@ffi.Native<ffi.Void Function(ffi.Pointer<llama_context>)>()
external void llama_free(ffi.Pointer<llama_context> ctx);

@ffi.Native<ffi.Pointer<llama_memory_i> Function(ffi.Pointer<llama_context>)>()
external ffi.Pointer<llama_memory_i> llama_get_memory(
  ffi.Pointer<llama_context> ctx,
);

@ffi.Native<
  ffi.Pointer<llama_context> Function(
    ffi.Pointer<llama_model>,
    llama_context_params,
  )
>()
external ffi.Pointer<llama_context> llama_init_from_model(
  ffi.Pointer<llama_model> model,
  llama_context_params params,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.UnsignedInt level,
          ffi.Pointer<ffi.Char> text,
          ffi.Pointer<ffi.Void> user_data,
        )
      >
    >,
    ffi.Pointer<ffi.Void>,
  )
>()
external void llama_log_set(
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.UnsignedInt level,
        ffi.Pointer<ffi.Char> text,
        ffi.Pointer<ffi.Void> user_data,
      )
    >
  >
  log_callback,
  ffi.Pointer<ffi.Void> user_data,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<llama_memory_i>, ffi.Bool)>()
external void llama_memory_clear(ffi.Pointer<llama_memory_i> mem, bool data);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.Pointer<llama_model>,
    ffi.Pointer<ffi.Char>,
  )
>()
external ffi.Pointer<ffi.Char> llama_model_chat_template(
  ffi.Pointer<llama_model> model,
  ffi.Pointer<ffi.Char> name,
);

@ffi.Native<llama_model_params Function()>()
external llama_model_params llama_model_default_params();

@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<llama_model>, ffi.Pointer<ffi.Char>, ffi.Size)
>()
external int llama_model_desc(
  ffi.Pointer<llama_model> model,
  ffi.Pointer<ffi.Char> buf,
  int buf_size,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<llama_model>)>()
external void llama_model_free(ffi.Pointer<llama_model> model);

@ffi.Native<ffi.Pointer<llama_vocab> Function(ffi.Pointer<llama_model>)>()
external ffi.Pointer<llama_vocab> llama_model_get_vocab(
  ffi.Pointer<llama_model> model,
);

@ffi.Native<
  ffi.Pointer<llama_model> Function(ffi.Pointer<ffi.Char>, llama_model_params)
>()
external ffi.Pointer<llama_model> llama_model_load_from_file(
  ffi.Pointer<ffi.Char> path_model,
  llama_model_params params,
);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<llama_model>)>()
external int llama_model_n_ctx_train(ffi.Pointer<llama_model> model);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<llama_model>)>()
external int llama_model_n_layer(ffi.Pointer<llama_model> model);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<llama_context>)>()
external int llama_n_batch(ffi.Pointer<llama_context> ctx);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<llama_context>)>()
external int llama_n_ctx(ffi.Pointer<llama_context> ctx);

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> llama_print_system_info();

@ffi.Native<
  ffi.Void Function(ffi.Pointer<llama_sampler>, ffi.Pointer<llama_sampler>)
>()
external void llama_sampler_chain_add(
  ffi.Pointer<llama_sampler> chain,
  ffi.Pointer<llama_sampler> smpl,
);

@ffi.Native<llama_sampler_chain_params Function()>()
external llama_sampler_chain_params llama_sampler_chain_default_params();

@ffi.Native<ffi.Pointer<llama_sampler> Function(llama_sampler_chain_params)>()
external ffi.Pointer<llama_sampler> llama_sampler_chain_init(
  llama_sampler_chain_params params,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<llama_sampler>)>()
external void llama_sampler_free(ffi.Pointer<llama_sampler> smpl);

/// seed == LLAMA_DEFAULT_SEED to use a random seed.
@ffi.Native<ffi.Pointer<llama_sampler> Function(ffi.Uint32)>()
external ffi.Pointer<llama_sampler> llama_sampler_init_dist(int seed);

@ffi.Native<ffi.Pointer<llama_sampler> Function()>()
external ffi.Pointer<llama_sampler> llama_sampler_init_greedy();

/// #details Updates the logits l_i` = l_i/t. When t <= 0.0f, the maximum logit is kept at it's original value, the rest are set to -inf
@ffi.Native<ffi.Pointer<llama_sampler> Function(ffi.Float)>()
external ffi.Pointer<llama_sampler> llama_sampler_init_temp(double t);

/// @details Top-K sampling described in academic paper "The Curious Case of Neural Text Degeneration" https://arxiv.org/abs/1904.09751
/// Setting k <= 0 makes this a noop
@ffi.Native<ffi.Pointer<llama_sampler> Function(ffi.Int32)>()
external ffi.Pointer<llama_sampler> llama_sampler_init_top_k(int k);

/// @details Nucleus sampling described in academic paper "The Curious Case of Neural Text Degeneration" https://arxiv.org/abs/1904.09751
@ffi.Native<ffi.Pointer<llama_sampler> Function(ffi.Float, ffi.Size)>()
external ffi.Pointer<llama_sampler> llama_sampler_init_top_p(
  double p,
  int min_keep,
);

@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<llama_sampler>,
    ffi.Pointer<llama_context>,
    ffi.Int32,
  )
>()
external int llama_sampler_sample(
  ffi.Pointer<llama_sampler> smpl,
  ffi.Pointer<llama_context> ctx,
  int idx,
);

@ffi.Native<ffi.Bool Function()>()
external bool llama_supports_gpu_offload();

@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<llama_vocab>,
    ffi.Int32,
    ffi.Pointer<ffi.Char>,
    ffi.Int32,
    ffi.Int32,
    ffi.Bool,
  )
>()
external int llama_token_to_piece(
  ffi.Pointer<llama_vocab> vocab,
  int token,
  ffi.Pointer<ffi.Char> buf,
  int length,
  int lstrip,
  bool special,
);

/// @details Convert the provided text into tokens.
/// @param tokens The tokens pointer must be large enough to hold the resulting tokens.
/// @return Returns the number of tokens on success, no more than n_tokens_max
/// @return Returns a negative number on failure - the number of tokens that would have been returned
/// @return Returns INT32_MIN on overflow (e.g., tokenization result size exceeds int32_t limit)
/// @param add_special Allow to add BOS and EOS tokens if model is configured to do so.
/// @param parse_special Allow tokenizing special and/or control tokens which otherwise are not exposed and treated
/// as plaintext. Does not insert a leading space.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<llama_vocab>,
    ffi.Pointer<ffi.Char>,
    ffi.Int32,
    ffi.Pointer<ffi.Int32>,
    ffi.Int32,
    ffi.Bool,
    ffi.Bool,
  )
>()
external int llama_tokenize(
  ffi.Pointer<llama_vocab> vocab,
  ffi.Pointer<ffi.Char> text,
  int text_len,
  ffi.Pointer<ffi.Int32> tokens,
  int n_tokens_max,
  bool add_special,
  bool parse_special,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<llama_vocab>, ffi.Int32)>()
external bool llama_vocab_is_eog(ffi.Pointer<llama_vocab> vocab, int token);

final class ggml_backend_device extends ffi.Opaque {}

enum ggml_log_level {
  GGML_LOG_LEVEL_NONE(0),
  GGML_LOG_LEVEL_DEBUG(1),
  GGML_LOG_LEVEL_INFO(2),
  GGML_LOG_LEVEL_WARN(3),
  GGML_LOG_LEVEL_ERROR(4),
  GGML_LOG_LEVEL_CONT(5);

  final int value;
  const ggml_log_level(this.value);

  static ggml_log_level fromValue(int value) => switch (value) {
    0 => GGML_LOG_LEVEL_NONE,
    1 => GGML_LOG_LEVEL_DEBUG,
    2 => GGML_LOG_LEVEL_INFO,
    3 => GGML_LOG_LEVEL_WARN,
    4 => GGML_LOG_LEVEL_ERROR,
    5 => GGML_LOG_LEVEL_CONT,
    _ => throw ArgumentError('Unknown value for ggml_log_level: $value'),
  };
}

final class ggml_tensor extends ffi.Opaque {}

enum ggml_type {
  GGML_TYPE_F32(0),
  GGML_TYPE_F16(1),
  GGML_TYPE_Q4_0(2),
  GGML_TYPE_Q4_1(3),
  GGML_TYPE_Q5_0(6),
  GGML_TYPE_Q5_1(7),
  GGML_TYPE_Q8_0(8),
  GGML_TYPE_Q8_1(9),
  GGML_TYPE_Q2_K(10),
  GGML_TYPE_Q3_K(11),
  GGML_TYPE_Q4_K(12),
  GGML_TYPE_Q5_K(13),
  GGML_TYPE_Q6_K(14),
  GGML_TYPE_Q8_K(15),
  GGML_TYPE_IQ2_XXS(16),
  GGML_TYPE_IQ2_XS(17),
  GGML_TYPE_IQ3_XXS(18),
  GGML_TYPE_IQ1_S(19),
  GGML_TYPE_IQ4_NL(20),
  GGML_TYPE_IQ3_S(21),
  GGML_TYPE_IQ2_S(22),
  GGML_TYPE_IQ4_XS(23),
  GGML_TYPE_I8(24),
  GGML_TYPE_I16(25),
  GGML_TYPE_I32(26),
  GGML_TYPE_I64(27),
  GGML_TYPE_F64(28),
  GGML_TYPE_IQ1_M(29),
  GGML_TYPE_BF16(30),
  GGML_TYPE_TQ1_0(34),
  GGML_TYPE_TQ2_0(35),
  GGML_TYPE_MXFP4(39),
  GGML_TYPE_NVFP4(40),
  GGML_TYPE_Q1_0(41),
  GGML_TYPE_Q2_0(42),
  GGML_TYPE_COUNT(43);

  final int value;
  const ggml_type(this.value);

  static ggml_type fromValue(int value) => switch (value) {
    0 => GGML_TYPE_F32,
    1 => GGML_TYPE_F16,
    2 => GGML_TYPE_Q4_0,
    3 => GGML_TYPE_Q4_1,
    6 => GGML_TYPE_Q5_0,
    7 => GGML_TYPE_Q5_1,
    8 => GGML_TYPE_Q8_0,
    9 => GGML_TYPE_Q8_1,
    10 => GGML_TYPE_Q2_K,
    11 => GGML_TYPE_Q3_K,
    12 => GGML_TYPE_Q4_K,
    13 => GGML_TYPE_Q5_K,
    14 => GGML_TYPE_Q6_K,
    15 => GGML_TYPE_Q8_K,
    16 => GGML_TYPE_IQ2_XXS,
    17 => GGML_TYPE_IQ2_XS,
    18 => GGML_TYPE_IQ3_XXS,
    19 => GGML_TYPE_IQ1_S,
    20 => GGML_TYPE_IQ4_NL,
    21 => GGML_TYPE_IQ3_S,
    22 => GGML_TYPE_IQ2_S,
    23 => GGML_TYPE_IQ4_XS,
    24 => GGML_TYPE_I8,
    25 => GGML_TYPE_I16,
    26 => GGML_TYPE_I32,
    27 => GGML_TYPE_I64,
    28 => GGML_TYPE_F64,
    29 => GGML_TYPE_IQ1_M,
    30 => GGML_TYPE_BF16,
    34 => GGML_TYPE_TQ1_0,
    35 => GGML_TYPE_TQ2_0,
    39 => GGML_TYPE_MXFP4,
    40 => GGML_TYPE_NVFP4,
    41 => GGML_TYPE_Q1_0,
    42 => GGML_TYPE_Q2_0,
    43 => GGML_TYPE_COUNT,
    _ => throw ArgumentError('Unknown value for ggml_type: $value'),
  };
}

enum llama_attention_type {
  LLAMA_ATTENTION_TYPE_UNSPECIFIED(-1),
  LLAMA_ATTENTION_TYPE_CAUSAL(0),
  LLAMA_ATTENTION_TYPE_NON_CAUSAL(1);

  final int value;
  const llama_attention_type(this.value);

  static llama_attention_type fromValue(int value) => switch (value) {
    -1 => LLAMA_ATTENTION_TYPE_UNSPECIFIED,
    0 => LLAMA_ATTENTION_TYPE_CAUSAL,
    1 => LLAMA_ATTENTION_TYPE_NON_CAUSAL,
    _ => throw ArgumentError('Unknown value for llama_attention_type: $value'),
  };
}

final class llama_batch extends ffi.Struct {
  @ffi.Int32()
  external int n_tokens;

  external ffi.Pointer<ffi.Int32> token;

  external ffi.Pointer<ffi.Float> embd;

  external ffi.Pointer<ffi.Int32> pos;

  external ffi.Pointer<ffi.Int32> n_seq_id;

  external ffi.Pointer<ffi.Pointer<ffi.Int32>> seq_id;

  external ffi.Pointer<ffi.Int8> logits;

  static ffi.Pointer<llama_batch> $allocate(
    ffi.Allocator $allocator, {
    required int n_tokens,
    required ffi.Pointer<ffi.Int32> token,
    required ffi.Pointer<ffi.Float> embd,
    required ffi.Pointer<ffi.Int32> pos,
    required ffi.Pointer<ffi.Int32> n_seq_id,
    required ffi.Pointer<ffi.Pointer<ffi.Int32>> seq_id,
    required ffi.Pointer<ffi.Int8> logits,
  }) => $allocator<llama_batch>()
    ..ref.n_tokens = n_tokens
    ..ref.token = token
    ..ref.embd = embd
    ..ref.pos = pos
    ..ref.n_seq_id = n_seq_id
    ..ref.seq_id = seq_id
    ..ref.logits = logits;
}

final class llama_chat_message extends ffi.Struct {
  external ffi.Pointer<ffi.Char> role;

  external ffi.Pointer<ffi.Char> content;

  static ffi.Pointer<llama_chat_message> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> role,
    required ffi.Pointer<ffi.Char> content,
  }) => $allocator<llama_chat_message>()
    ..ref.role = role
    ..ref.content = content;
}

final class llama_context extends ffi.Opaque {}

final class llama_context_params extends ffi.Struct {
  @ffi.Uint32()
  external int n_ctx;

  @ffi.Uint32()
  external int n_batch;

  @ffi.Uint32()
  external int n_ubatch;

  @ffi.Uint32()
  external int n_seq_max;

  @ffi.Uint32()
  external int n_rs_seq;

  @ffi.Uint32()
  external int n_outputs_max;

  @ffi.Uint32()
  external int n_outputs_max_per_seq;

  @ffi.Int32()
  external int n_threads;

  @ffi.Int32()
  external int n_threads_batch;

  @ffi.UnsignedInt()
  external int ctx_typeAsInt;

  llama_context_type get ctx_type =>
      llama_context_type.fromValue(ctx_typeAsInt);
  set ctx_type(llama_context_type value) => ctx_typeAsInt = value.value;

  @ffi.Int()
  external int rope_scaling_typeAsInt;

  llama_rope_scaling_type get rope_scaling_type =>
      llama_rope_scaling_type.fromValue(rope_scaling_typeAsInt);
  set rope_scaling_type(llama_rope_scaling_type value) =>
      rope_scaling_typeAsInt = value.value;

  @ffi.Int()
  external int pooling_typeAsInt;

  llama_pooling_type get pooling_type =>
      llama_pooling_type.fromValue(pooling_typeAsInt);
  set pooling_type(llama_pooling_type value) => pooling_typeAsInt = value.value;

  @ffi.Int()
  external int attention_typeAsInt;

  llama_attention_type get attention_type =>
      llama_attention_type.fromValue(attention_typeAsInt);
  set attention_type(llama_attention_type value) =>
      attention_typeAsInt = value.value;

  @ffi.Int()
  external int flash_attn_typeAsInt;

  llama_flash_attn_type get flash_attn_type =>
      llama_flash_attn_type.fromValue(flash_attn_typeAsInt);
  set flash_attn_type(llama_flash_attn_type value) =>
      flash_attn_typeAsInt = value.value;

  @ffi.Float()
  external double rope_freq_base;

  @ffi.Float()
  external double rope_freq_scale;

  @ffi.Float()
  external double yarn_ext_factor;

  @ffi.Float()
  external double yarn_attn_factor;

  @ffi.Float()
  external double yarn_beta_fast;

  @ffi.Float()
  external double yarn_beta_slow;

  @ffi.Uint32()
  external int yarn_orig_ctx;

  @ffi.Float()
  external double defrag_thold;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Bool Function(
        ffi.Pointer<ggml_tensor> t,
        ffi.Bool ask,
        ffi.Pointer<ffi.Void> user_data,
      )
    >
  >
  cb_eval;

  external ffi.Pointer<ffi.Void> cb_eval_user_data;

  @ffi.UnsignedInt()
  external int type_kAsInt;

  ggml_type get type_k => ggml_type.fromValue(type_kAsInt);
  set type_k(ggml_type value) => type_kAsInt = value.value;

  @ffi.UnsignedInt()
  external int type_vAsInt;

  ggml_type get type_v => ggml_type.fromValue(type_vAsInt);
  set type_v(ggml_type value) => type_vAsInt = value.value;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Void> data)>
  >
  abort_callback;

  external ffi.Pointer<ffi.Void> abort_callback_data;

  @ffi.Bool()
  external bool embeddings;

  @ffi.Bool()
  external bool offload_kqv;

  @ffi.Bool()
  external bool no_perf;

  @ffi.Bool()
  external bool op_offload;

  @ffi.Bool()
  external bool swa_full;

  @ffi.Bool()
  external bool kv_unified;

  external ffi.Pointer<llama_sampler_seq_config> samplers;

  @ffi.Size()
  external int n_samplers;

  external ffi.Pointer<llama_context> ctx_other;

  static ffi.Pointer<llama_context_params> $allocate(
    ffi.Allocator $allocator, {
    required int n_ctx,
    required int n_batch,
    required int n_ubatch,
    required int n_seq_max,
    required int n_rs_seq,
    required int n_outputs_max,
    required int n_outputs_max_per_seq,
    required int n_threads,
    required int n_threads_batch,
    required llama_context_type ctx_type,
    required llama_rope_scaling_type rope_scaling_type,
    required llama_pooling_type pooling_type,
    required llama_attention_type attention_type,
    required llama_flash_attn_type flash_attn_type,
    required double rope_freq_base,
    required double rope_freq_scale,
    required double yarn_ext_factor,
    required double yarn_attn_factor,
    required double yarn_beta_fast,
    required double yarn_beta_slow,
    required int yarn_orig_ctx,
    required double defrag_thold,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<ggml_tensor> t,
          ffi.Bool ask,
          ffi.Pointer<ffi.Void> user_data,
        )
      >
    >
    cb_eval,
    required ffi.Pointer<ffi.Void> cb_eval_user_data,
    required ggml_type type_k,
    required ggml_type type_v,
    required ffi.Pointer<
      ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Void> data)>
    >
    abort_callback,
    required ffi.Pointer<ffi.Void> abort_callback_data,
    required bool embeddings,
    required bool offload_kqv,
    required bool no_perf,
    required bool op_offload,
    required bool swa_full,
    required bool kv_unified,
    required ffi.Pointer<llama_sampler_seq_config> samplers,
    required int n_samplers,
    required ffi.Pointer<llama_context> ctx_other,
  }) => $allocator<llama_context_params>()
    ..ref.n_ctx = n_ctx
    ..ref.n_batch = n_batch
    ..ref.n_ubatch = n_ubatch
    ..ref.n_seq_max = n_seq_max
    ..ref.n_rs_seq = n_rs_seq
    ..ref.n_outputs_max = n_outputs_max
    ..ref.n_outputs_max_per_seq = n_outputs_max_per_seq
    ..ref.n_threads = n_threads
    ..ref.n_threads_batch = n_threads_batch
    ..ref.ctx_type = ctx_type
    ..ref.rope_scaling_type = rope_scaling_type
    ..ref.pooling_type = pooling_type
    ..ref.attention_type = attention_type
    ..ref.flash_attn_type = flash_attn_type
    ..ref.rope_freq_base = rope_freq_base
    ..ref.rope_freq_scale = rope_freq_scale
    ..ref.yarn_ext_factor = yarn_ext_factor
    ..ref.yarn_attn_factor = yarn_attn_factor
    ..ref.yarn_beta_fast = yarn_beta_fast
    ..ref.yarn_beta_slow = yarn_beta_slow
    ..ref.yarn_orig_ctx = yarn_orig_ctx
    ..ref.defrag_thold = defrag_thold
    ..ref.cb_eval = cb_eval
    ..ref.cb_eval_user_data = cb_eval_user_data
    ..ref.type_k = type_k
    ..ref.type_v = type_v
    ..ref.abort_callback = abort_callback
    ..ref.abort_callback_data = abort_callback_data
    ..ref.embeddings = embeddings
    ..ref.offload_kqv = offload_kqv
    ..ref.no_perf = no_perf
    ..ref.op_offload = op_offload
    ..ref.swa_full = swa_full
    ..ref.kv_unified = kv_unified
    ..ref.samplers = samplers
    ..ref.n_samplers = n_samplers
    ..ref.ctx_other = ctx_other;
}

enum llama_context_type {
  LLAMA_CONTEXT_TYPE_DEFAULT(0),
  LLAMA_CONTEXT_TYPE_MTP(1);

  final int value;
  const llama_context_type(this.value);

  static llama_context_type fromValue(int value) => switch (value) {
    0 => LLAMA_CONTEXT_TYPE_DEFAULT,
    1 => LLAMA_CONTEXT_TYPE_MTP,
    _ => throw ArgumentError('Unknown value for llama_context_type: $value'),
  };
}

enum llama_flash_attn_type {
  LLAMA_FLASH_ATTN_TYPE_AUTO(-1),
  LLAMA_FLASH_ATTN_TYPE_DISABLED(0),
  LLAMA_FLASH_ATTN_TYPE_ENABLED(1);

  final int value;
  const llama_flash_attn_type(this.value);

  static llama_flash_attn_type fromValue(int value) => switch (value) {
    -1 => LLAMA_FLASH_ATTN_TYPE_AUTO,
    0 => LLAMA_FLASH_ATTN_TYPE_DISABLED,
    1 => LLAMA_FLASH_ATTN_TYPE_ENABLED,
    _ => throw ArgumentError('Unknown value for llama_flash_attn_type: $value'),
  };
}

enum llama_lazy_mode {
  LLAMA_LAZY_MODE_OFF(0),
  LLAMA_LAZY_MODE_AUTO(1),
  LLAMA_LAZY_MODE_ON(2);

  final int value;
  const llama_lazy_mode(this.value);

  static llama_lazy_mode fromValue(int value) => switch (value) {
    0 => LLAMA_LAZY_MODE_OFF,
    1 => LLAMA_LAZY_MODE_AUTO,
    2 => LLAMA_LAZY_MODE_ON,
    _ => throw ArgumentError('Unknown value for llama_lazy_mode: $value'),
  };
}

enum llama_load_mode {
  LLAMA_LOAD_MODE_AUTO(-1),
  LLAMA_LOAD_MODE_NONE(0),
  LLAMA_LOAD_MODE_MMAP(1),
  LLAMA_LOAD_MODE_MLOCK(2),
  LLAMA_LOAD_MODE_MMAP_MLOCK(3),
  LLAMA_LOAD_MODE_DIRECT_IO(4);

  final int value;
  const llama_load_mode(this.value);

  static llama_load_mode fromValue(int value) => switch (value) {
    -1 => LLAMA_LOAD_MODE_AUTO,
    0 => LLAMA_LOAD_MODE_NONE,
    1 => LLAMA_LOAD_MODE_MMAP,
    2 => LLAMA_LOAD_MODE_MLOCK,
    3 => LLAMA_LOAD_MODE_MMAP_MLOCK,
    4 => LLAMA_LOAD_MODE_DIRECT_IO,
    _ => throw ArgumentError('Unknown value for llama_load_mode: $value'),
  };
}

final class llama_memory_i extends ffi.Opaque {}

final class llama_model extends ffi.Opaque {}

final class llama_model_kv_override extends ffi.Opaque {}

final class llama_model_params extends ffi.Struct {
  external ffi.Pointer<ffi.Pointer<ggml_backend_device>> devices;

  external ffi.Pointer<llama_model_tensor_buft_override> tensor_buft_overrides;

  @ffi.Int32()
  external int n_gpu_layers;

  @ffi.UnsignedInt()
  external int split_modeAsInt;

  llama_split_mode get split_mode =>
      llama_split_mode.fromValue(split_modeAsInt);
  set split_mode(llama_split_mode value) => split_modeAsInt = value.value;

  @ffi.Int()
  external int load_modeAsInt;

  llama_load_mode get load_mode => llama_load_mode.fromValue(load_modeAsInt);
  set load_mode(llama_load_mode value) => load_modeAsInt = value.value;

  @ffi.UnsignedInt()
  external int lazy_modeAsInt;

  llama_lazy_mode get lazy_mode => llama_lazy_mode.fromValue(lazy_modeAsInt);
  set lazy_mode(llama_lazy_mode value) => lazy_modeAsInt = value.value;

  @ffi.Int32()
  external int main_gpu;

  external ffi.Pointer<ffi.Float> tensor_split;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Bool Function(ffi.Float progress, ffi.Pointer<ffi.Void> user_data)
    >
  >
  progress_callback;

  external ffi.Pointer<ffi.Void> progress_callback_user_data;

  external ffi.Pointer<llama_model_kv_override> kv_overrides;

  @ffi.Bool()
  external bool vocab_only;

  @ffi.Bool()
  external bool check_tensors;

  @ffi.Bool()
  external bool use_extra_bufts;

  @ffi.Bool()
  external bool no_host;

  @ffi.Bool()
  external bool no_alloc;

  @ffi.Bool()
  external bool load_mtp;

  static ffi.Pointer<llama_model_params> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Pointer<ggml_backend_device>> devices,
    required ffi.Pointer<llama_model_tensor_buft_override>
    tensor_buft_overrides,
    required int n_gpu_layers,
    required llama_split_mode split_mode,
    required llama_load_mode load_mode,
    required llama_lazy_mode lazy_mode,
    required int main_gpu,
    required ffi.Pointer<ffi.Float> tensor_split,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Bool Function(ffi.Float progress, ffi.Pointer<ffi.Void> user_data)
      >
    >
    progress_callback,
    required ffi.Pointer<ffi.Void> progress_callback_user_data,
    required ffi.Pointer<llama_model_kv_override> kv_overrides,
    required bool vocab_only,
    required bool check_tensors,
    required bool use_extra_bufts,
    required bool no_host,
    required bool no_alloc,
    required bool load_mtp,
  }) => $allocator<llama_model_params>()
    ..ref.devices = devices
    ..ref.tensor_buft_overrides = tensor_buft_overrides
    ..ref.n_gpu_layers = n_gpu_layers
    ..ref.split_mode = split_mode
    ..ref.load_mode = load_mode
    ..ref.lazy_mode = lazy_mode
    ..ref.main_gpu = main_gpu
    ..ref.tensor_split = tensor_split
    ..ref.progress_callback = progress_callback
    ..ref.progress_callback_user_data = progress_callback_user_data
    ..ref.kv_overrides = kv_overrides
    ..ref.vocab_only = vocab_only
    ..ref.check_tensors = check_tensors
    ..ref.use_extra_bufts = use_extra_bufts
    ..ref.no_host = no_host
    ..ref.no_alloc = no_alloc
    ..ref.load_mtp = load_mtp;
}

final class llama_model_tensor_buft_override extends ffi.Opaque {}

enum llama_pooling_type {
  LLAMA_POOLING_TYPE_UNSPECIFIED(-1),
  LLAMA_POOLING_TYPE_NONE(0),
  LLAMA_POOLING_TYPE_MEAN(1),
  LLAMA_POOLING_TYPE_CLS(2),
  LLAMA_POOLING_TYPE_LAST(3),
  LLAMA_POOLING_TYPE_RANK(4);

  final int value;
  const llama_pooling_type(this.value);

  static llama_pooling_type fromValue(int value) => switch (value) {
    -1 => LLAMA_POOLING_TYPE_UNSPECIFIED,
    0 => LLAMA_POOLING_TYPE_NONE,
    1 => LLAMA_POOLING_TYPE_MEAN,
    2 => LLAMA_POOLING_TYPE_CLS,
    3 => LLAMA_POOLING_TYPE_LAST,
    4 => LLAMA_POOLING_TYPE_RANK,
    _ => throw ArgumentError('Unknown value for llama_pooling_type: $value'),
  };
}

enum llama_rope_scaling_type {
  LLAMA_ROPE_SCALING_TYPE_UNSPECIFIED(-1),
  LLAMA_ROPE_SCALING_TYPE_NONE(0),
  LLAMA_ROPE_SCALING_TYPE_LINEAR(1),
  LLAMA_ROPE_SCALING_TYPE_YARN(2),
  LLAMA_ROPE_SCALING_TYPE_LONGROPE(3);

  static const LLAMA_ROPE_SCALING_TYPE_MAX_VALUE =
      LLAMA_ROPE_SCALING_TYPE_LONGROPE;

  final int value;
  const llama_rope_scaling_type(this.value);

  static llama_rope_scaling_type fromValue(int value) => switch (value) {
    -1 => LLAMA_ROPE_SCALING_TYPE_UNSPECIFIED,
    0 => LLAMA_ROPE_SCALING_TYPE_NONE,
    1 => LLAMA_ROPE_SCALING_TYPE_LINEAR,
    2 => LLAMA_ROPE_SCALING_TYPE_YARN,
    3 => LLAMA_ROPE_SCALING_TYPE_LONGROPE,
    _ => throw ArgumentError(
      'Unknown value for llama_rope_scaling_type: $value',
    ),
  };

  @override
  String toString() {
    if (this == LLAMA_ROPE_SCALING_TYPE_LONGROPE)
      return "llama_rope_scaling_type.LLAMA_ROPE_SCALING_TYPE_LONGROPE, llama_rope_scaling_type.LLAMA_ROPE_SCALING_TYPE_MAX_VALUE";
    return super.toString();
  }
}

final class llama_sampler extends ffi.Opaque {}

final class llama_sampler_chain_params extends ffi.Struct {
  @ffi.Bool()
  external bool no_perf;

  static ffi.Pointer<llama_sampler_chain_params> $allocate(
    ffi.Allocator $allocator, {
    required bool no_perf,
  }) => $allocator<llama_sampler_chain_params>()..ref.no_perf = no_perf;
}

final class llama_sampler_seq_config extends ffi.Opaque {}

enum llama_split_mode {
  LLAMA_SPLIT_MODE_NONE(0),
  LLAMA_SPLIT_MODE_LAYER(1),
  LLAMA_SPLIT_MODE_ROW(2),
  LLAMA_SPLIT_MODE_TENSOR(3);

  final int value;
  const llama_split_mode(this.value);

  static llama_split_mode fromValue(int value) => switch (value) {
    0 => LLAMA_SPLIT_MODE_NONE,
    1 => LLAMA_SPLIT_MODE_LAYER,
    2 => LLAMA_SPLIT_MODE_ROW,
    3 => LLAMA_SPLIT_MODE_TENSOR,
    _ => throw ArgumentError('Unknown value for llama_split_mode: $value'),
  };
}

final class llama_vocab extends ffi.Opaque {}
