/// Purpose: Templates for common chat providers, all through their
/// OpenAI-compatible `chat/completions` API.
/// Inputs: None.
/// Returns: [chatProviderTemplates].
/// Side effects: None.
/// Notes: A flat list sorted by name, never grouped by region. Where a
/// provider runs several sites, one template lists them as endpoints labelled
/// in the provider's own words, or by domain when it names none. Base URLs
/// were checked against each provider's documentation and the models.dev
/// `api` field (October 2026). Template ids are a compatibility contract and
/// never change. None is seeded: they are offered only when adding a source.
library;

import 'provider.dart';
import 'templates.dart';

/// Every chat template besides OpenAI, OpenRouter and custom.
const chatProviderTemplates = <OnlineProviderTemplate>[
  OnlineProviderTemplate(
    id: 'anthropic',
    name: 'Anthropic',
    dialect: OnlineDialect.openaiCompatible,
    defaultBaseUrl: 'https://api.anthropic.com/v1',
    iconKey: 'anthropic',
    catalogId: 'anthropic',
    docsUrl: 'https://docs.claude.com/en/api/openai-sdk',
  ),
  OnlineProviderTemplate(
    id: 'gemini',
    name: 'Google Gemini',
    dialect: OnlineDialect.openaiCompatible,
    defaultBaseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    iconKey: 'gemini',
    catalogId: 'google',
    docsUrl: 'https://ai.google.dev/gemini-api/docs/openai',
  ),
  OnlineProviderTemplate(
    id: 'deepseek',
    name: 'DeepSeek',
    dialect: OnlineDialect.openaiCompatible,
    defaultBaseUrl: 'https://api.deepseek.com/v1',
    iconKey: 'deepseek',
    catalogId: 'deepseek',
    docsUrl: 'https://api-docs.deepseek.com',
  ),
  OnlineProviderTemplate(
    id: 'xai',
    name: 'xAI',
    dialect: OnlineDialect.openaiCompatible,
    defaultBaseUrl: 'https://api.x.ai/v1',
    iconKey: 'xai',
    catalogId: 'xai',
    docsUrl: 'https://docs.x.ai/docs/models',
  ),
  OnlineProviderTemplate(
    id: 'mistral',
    name: 'Mistral AI',
    dialect: OnlineDialect.openaiCompatible,
    defaultBaseUrl: 'https://api.mistral.ai/v1',
    iconKey: 'mistral',
    catalogId: 'mistral',
    docsUrl: 'https://docs.mistral.ai/api/',
  ),
  OnlineProviderTemplate(
    id: 'groq',
    name: 'Groq',
    dialect: OnlineDialect.openaiCompatible,
    defaultBaseUrl: 'https://api.groq.com/openai/v1',
    iconKey: 'groq',
    catalogId: 'groq',
    docsUrl: 'https://console.groq.com/docs/openai',
  ),
  OnlineProviderTemplate(
    id: 'together',
    name: 'Together AI',
    dialect: OnlineDialect.openaiCompatible,
    defaultBaseUrl: 'https://api.together.xyz/v1',
    iconKey: 'together',
    catalogId: 'togetherai',
    docsUrl: 'https://docs.together.ai/docs/openai-api-compatibility',
  ),
  OnlineProviderTemplate(
    id: 'fireworks',
    name: 'Fireworks AI',
    dialect: OnlineDialect.openaiCompatible,
    defaultBaseUrl: 'https://api.fireworks.ai/inference/v1',
    iconKey: 'fireworks',
    catalogId: 'fireworks-ai',
    docsUrl: 'https://fireworks.ai/docs/tools-sdks/openai-compatibility',
  ),
  OnlineProviderTemplate(
    id: 'cerebras',
    name: 'Cerebras',
    dialect: OnlineDialect.openaiCompatible,
    defaultBaseUrl: 'https://api.cerebras.ai/v1',
    iconKey: 'cerebras',
    catalogId: 'cerebras',
    docsUrl: 'https://inference-docs.cerebras.ai/resources/openai',
  ),
  OnlineProviderTemplate(
    id: 'deepinfra',
    name: 'Deep Infra',
    dialect: OnlineDialect.openaiCompatible,
    defaultBaseUrl: 'https://api.deepinfra.com/v1/openai',
    iconKey: 'deepinfra',
    catalogId: 'deepinfra',
    docsUrl: 'https://deepinfra.com/docs/openai_api',
  ),
  OnlineProviderTemplate(
    id: 'moonshot',
    name: 'Moonshot AI (Kimi)',
    dialect: OnlineDialect.openaiCompatible,
    defaultBaseUrl: 'https://api.moonshot.ai/v1',
    iconKey: 'moonshot',
    catalogId: 'moonshotai',
    docsUrl: 'https://platform.moonshot.ai/docs/api/chat',
    endpoints: [
      OnlineEndpointOption(
        'https://api.moonshot.ai/v1',
        catalogId: 'moonshotai',
      ),
      OnlineEndpointOption(
        'https://api.moonshot.cn/v1',
        catalogId: 'moonshotai-cn',
      ),
    ],
  ),
  OnlineProviderTemplate(
    id: 'zhipu',
    name: 'Z.ai / BigModel',
    dialect: OnlineDialect.openaiCompatible,
    defaultBaseUrl: 'https://api.z.ai/api/paas/v4',
    iconKey: 'zhipu',
    catalogId: 'zai',
    docsUrl: 'https://docs.z.ai/guides/develop/openai/introduction',
    endpoints: [
      OnlineEndpointOption(
        'https://api.z.ai/api/paas/v4',
        label: 'Z.ai',
        catalogId: 'zai',
      ),
      OnlineEndpointOption(
        'https://open.bigmodel.cn/api/paas/v4',
        label: 'BigModel',
        catalogId: 'zhipuai',
      ),
    ],
  ),
  OnlineProviderTemplate(
    id: 'dashscope',
    name: 'Alibaba Cloud Model Studio',
    dialect: OnlineDialect.openaiCompatible,
    defaultBaseUrl: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
    iconKey: 'qwen',
    catalogId: 'alibaba',
    docsUrl:
        'https://www.alibabacloud.com/help/en/model-studio/compatibility-of-openai-with-dashscope',
    endpoints: [
      OnlineEndpointOption(
        'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
        label: 'International (Singapore)',
        catalogId: 'alibaba',
      ),
      OnlineEndpointOption(
        'https://dashscope.aliyuncs.com/compatible-mode/v1',
        label: 'China (Beijing)',
        catalogId: 'alibaba-cn',
      ),
    ],
  ),
  OnlineProviderTemplate(
    id: 'siliconflow',
    name: 'SiliconFlow',
    dialect: OnlineDialect.openaiCompatible,
    defaultBaseUrl: 'https://api.siliconflow.com/v1',
    iconKey: 'siliconflow',
    catalogId: 'siliconflow',
    docsUrl: 'https://docs.siliconflow.com',
    endpoints: [
      OnlineEndpointOption(
        'https://api.siliconflow.com/v1',
        catalogId: 'siliconflow',
      ),
      OnlineEndpointOption(
        'https://api.siliconflow.cn/v1',
        catalogId: 'siliconflow-cn',
      ),
    ],
  ),
  OnlineProviderTemplate(
    id: 'volcengine',
    name: 'Volcengine Ark',
    dialect: OnlineDialect.openaiCompatible,
    defaultBaseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    iconKey: 'volcengine',
    catalogId: 'volcengine',
    docsUrl: 'https://www.volcengine.com/docs/82379/1330626',
  ),
  OnlineProviderTemplate(
    id: 'minimax',
    name: 'MiniMax',
    dialect: OnlineDialect.openaiCompatible,
    defaultBaseUrl: 'https://api.minimax.io/v1',
    iconKey: 'minimax',
    catalogId: 'minimax',
    docsUrl: 'https://platform.minimax.io/docs/api-reference/text-openai-api',
    endpoints: [
      OnlineEndpointOption('https://api.minimax.io/v1', catalogId: 'minimax'),
      OnlineEndpointOption(
        'https://api.minimaxi.com/v1',
        catalogId: 'minimax-cn',
      ),
    ],
  ),
  OnlineProviderTemplate(
    id: 'stepfun',
    name: 'StepFun',
    dialect: OnlineDialect.openaiCompatible,
    defaultBaseUrl: 'https://api.stepfun.com/v1',
    iconKey: 'stepfun',
    catalogId: 'stepfun',
    docsUrl: 'https://platform.stepfun.com/docs/overview/concept',
  ),
  OnlineProviderTemplate(
    id: 'qianfan',
    name: 'Baidu Qianfan',
    dialect: OnlineDialect.openaiCompatible,
    defaultBaseUrl: 'https://qianfan.baidubce.com/v2',
    iconKey: 'baidu',
    docsUrl: 'https://cloud.baidu.com/doc/qianfan-api/s/3m7of64lb',
  ),
  OnlineProviderTemplate(
    id: 'hunyuan',
    name: 'Tencent Hunyuan',
    dialect: OnlineDialect.openaiCompatible,
    defaultBaseUrl: 'https://api.hunyuan.cloud.tencent.com/v1',
    iconKey: 'hunyuan',
    docsUrl: 'https://cloud.tencent.com/document/product/1729/111007',
  ),
  OnlineProviderTemplate(
    id: 'perplexity',
    name: 'Perplexity',
    dialect: OnlineDialect.openaiCompatible,
    defaultBaseUrl: 'https://api.perplexity.ai',
    iconKey: 'perplexity',
    catalogId: 'perplexity',
    docsUrl: 'https://docs.perplexity.ai/guides/chat-completions-guide',
  ),
  OnlineProviderTemplate(
    id: 'cohere',
    name: 'Cohere',
    dialect: OnlineDialect.openaiCompatible,
    defaultBaseUrl: 'https://api.cohere.ai/compatibility/v1',
    iconKey: 'cohere',
    catalogId: 'cohere',
    docsUrl: 'https://docs.cohere.com/docs/compatibility-api',
  ),
  OnlineProviderTemplate(
    id: 'nvidia',
    name: 'NVIDIA NIM',
    dialect: OnlineDialect.openaiCompatible,
    defaultBaseUrl: 'https://integrate.api.nvidia.com/v1',
    iconKey: 'nvidia',
    catalogId: 'nvidia',
    docsUrl: 'https://docs.api.nvidia.com/nim/reference/llm-apis',
  ),
  OnlineProviderTemplate(
    id: 'huggingface',
    name: 'Hugging Face Inference Providers',
    dialect: OnlineDialect.openaiCompatible,
    defaultBaseUrl: 'https://router.huggingface.co/v1',
    iconKey: 'huggingface',
    catalogId: 'huggingface',
    docsUrl: 'https://huggingface.co/docs/inference-providers',
  ),
  OnlineProviderTemplate(
    id: 'githubModels',
    name: 'GitHub Models',
    dialect: OnlineDialect.openaiCompatible,
    defaultBaseUrl: 'https://models.github.ai/inference',
    iconKey: 'github',
    docsUrl: 'https://docs.github.com/en/github-models',
  ),
  OnlineProviderTemplate(
    id: 'azureOpenai',
    name: 'Azure OpenAI',
    dialect: OnlineDialect.openaiCompatible,
    defaultBaseUrl: '',
    authScheme: OnlineAuthScheme.header,
    authHeaderName: 'api-key',
    iconKey: 'azure',
    catalogId: 'azure',
    docsUrl:
        'https://learn.microsoft.com/en-us/azure/ai-foundry/openai/api-version-lifecycle',
  ),
  OnlineProviderTemplate(
    id: 'ollama',
    name: 'Ollama',
    dialect: OnlineDialect.openaiCompatible,
    defaultBaseUrl: 'http://localhost:11434/v1',
    authScheme: OnlineAuthScheme.none,
    iconKey: 'ollama',
    docsUrl: 'https://docs.ollama.com/api/openai-compatibility',
    local: true,
  ),
  OnlineProviderTemplate(
    id: 'lmstudio',
    name: 'LM Studio',
    dialect: OnlineDialect.openaiCompatible,
    defaultBaseUrl: 'http://localhost:1234/v1',
    authScheme: OnlineAuthScheme.none,
    iconKey: 'lmstudio',
    docsUrl: 'https://lmstudio.ai/docs/app/api/endpoints/openai',
    local: true,
  ),
  OnlineProviderTemplate(
    id: 'llamacppServer',
    name: 'llama.cpp server',
    dialect: OnlineDialect.openaiCompatible,
    defaultBaseUrl: 'http://localhost:8080/v1',
    authScheme: OnlineAuthScheme.none,
    iconKey: 'llamacpp',
    docsUrl: 'https://github.com/ggml-org/llama.cpp/tree/master/tools/server',
    local: true,
  ),
];
