"""Regenerate the llama.cpp architecture list for the pinned upstream build.

Purpose: Write packages/myapps_ai_llm_llama/lib/src/architectures.g.dart, the
         set of GGUF `general.architecture` values the pinned llama.cpp loads.
Inputs:  Optional path to llama-arch.cpp; by default it is downloaded for the
         tag in packages/myapps_ai_llm_llama/native/binaries.json.
Returns: None.
Side effects: Overwrites the generated file.
Notes:   Run whenever binaries.json moves to a new upstream tag.
"""

import json
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PKG = ROOT / "packages/myapps_ai_llm_llama"


def main():
    """Purpose: Generate the file. Inputs: argv. Returns: None. Side effects: Writes it. Notes: None."""
    tag = json.loads((PKG / "native/binaries.json").read_text())["upstream"]["tag"]
    if len(sys.argv) > 1:
        source = Path(sys.argv[1]).read_text()
    else:
        url = f"https://raw.githubusercontent.com/ggml-org/llama.cpp/{tag}/src/llama-arch.cpp"
        with urllib.request.urlopen(url) as r:
            source = r.read().decode()
    names = sorted({m for m in re.findall(r'\{\s*LLM_ARCH_[A-Z0-9_]+,\s*"([^"]+)"\s*\}', source)
                    if m != "(unknown)"})
    lines = [
        "// GENERATED by tool/update_llama_architectures.py — do not edit.",
        f"// Source: ggml-org/llama.cpp {tag} src/llama-arch.cpp, {len(names)} names.",
        "",
        "part of 'gguf.dart';",
        "",
        "/// GGUF `general.architecture` values the pinned build loads.",
        "const llamaSupportedArchitectures = <String>{",
        *[f"  '{n}'," for n in names],
        "};",
    ]
    (PKG / "lib/src/architectures.g.dart").write_text("\n".join(lines) + "\n")
    print(f"Wrote {len(names)} architectures for {tag}")


if __name__ == "__main__":
    main()
