"""Regenerate the built-in online model catalog from a models.dev snapshot.

Purpose: Write packages/myapps_ai_online/lib/src/catalog.g.dart, the catalog
         used for names, context lengths and inputs until the user refreshes
         from the source itself, and when a source cannot list its models.
Inputs:  Optional path to a models.dev api.json (default: download
         https://models.dev/api.json). Run: python3 tool/update_model_catalog.py
Returns: None.
Side effects: Overwrites the generated Dart file.
Notes:   Only the providers the templates name are kept, and only chat models
         (text output). The file records the snapshot date. models.dev data
         is MIT licensed (github.com/sst/models.dev).
"""

import datetime
import json
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "packages/myapps_ai_online/lib/src/catalog.g.dart"

# models.dev provider id -> vendor to show, or None for hosts serving many
# vendors' models (the vendor then comes from the model id).
PROVIDERS = {
    "openai": "OpenAI", "anthropic": "Anthropic", "google": "Google",
    "openrouter": None, "deepseek": "DeepSeek", "xai": "xAI",
    "mistral": "Mistral", "groq": None, "togetherai": None,
    "fireworks-ai": None, "cerebras": None, "moonshotai": "MoonshotAI",
    "moonshotai-cn": "MoonshotAI", "zai": "Z.ai", "zhipuai": "Z.ai",
    "alibaba": "Qwen", "alibaba-cn": "Qwen", "siliconflow": None,
    "siliconflow-cn": None, "volcengine": None, "minimax": "MiniMax",
    "minimax-cn": "MiniMax", "perplexity": "Perplexity", "cohere": "Cohere",
    "nvidia": None, "huggingface": None, "azure": None, "stepfun": "StepFun",
    "deepinfra": None, "llama": "Meta",
}


def dart(s):
    """Purpose: Quote a Dart string. Inputs: s. Returns: literal. Side effects: None. Notes: Raw-safe."""
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'").replace("$", "\\$") + "'"


def main():
    """Purpose: Generate the file. Inputs: argv. Returns: None. Side effects: Writes OUT. Notes: None."""
    if len(sys.argv) > 1:
        data = json.loads(Path(sys.argv[1]).read_text())
        source = Path(sys.argv[1]).name
    else:
        with urllib.request.urlopen("https://models.dev/api.json") as r:
            data = json.load(r)
        source = "https://models.dev/api.json"
    lines = [
        "// GENERATED by tool/update_model_catalog.py — do not edit.",
        f"// Source: {source}, {datetime.date.today().isoformat()}; models.dev, MIT.",
        "",
        "part of 'catalog.dart';",
        "",
        "/// models.dev provider id → (vendor, {model id → (name, context, inputs)}).",
        "const _snapshot = <String, (String?, Map<String, (String, int?, String)>)>{",
    ]
    total = 0
    for pid, vendor in PROVIDERS.items():
        provider = data.get(pid)
        if not provider:
            continue
        rows = []
        for mid, m in sorted(provider.get("models", {}).items()):
            outputs = m.get("modalities", {}).get("output", ["text"])
            if "text" not in outputs:
                continue
            name = m.get("name") or mid
            ctx = m.get("limit", {}).get("context") or None
            inputs = ",".join(m.get("modalities", {}).get("input", ["text"]))
            rows.append(f"    {dart(mid)}: ({dart(name)}, {ctx if ctx else 'null'}, {dart(inputs)}),")
        total += len(rows)
        lines.append(f"  {dart(pid)}: ({dart(vendor) if vendor else 'null'}, {{")
        lines.extend(rows)
        lines.append("  }),")
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT.relative_to(ROOT)}: {total} models")


if __name__ == "__main__":
    main()
