/// Purpose: Regenerate the Dart bindings from the vendored llama.cpp headers.
/// Inputs: Optionally the path to `libclang` as the first argument; otherwise
/// Visual Studio's LLVM component on Windows, then ffigen's default places.
/// Returns: None.
/// Side effects: Rewrites `lib/src/llama_bindings.g.dart` and
/// `lib/src/ggml_bindings.g.dart`.
/// Notes: Run after the headers in `third_party/llama.cpp/include/` change,
/// which happens only when `native/binaries.json` moves to a new upstream
/// tag — the bindings must describe exactly the version the binaries were
/// built from. Run from this package: `dart run tool/ffigen.dart`.
library;

import 'dart:ffi' show Abi;
import 'dart:io';

import 'package:ffigen/ffigen.dart';

/// The llama.cpp entry points the backend uses; the structs and enums they
/// reference come along.
const _llamaFunctions = {
  'llama_backend_init',
  'llama_print_system_info',
  'llama_log_set',
  'llama_supports_gpu_offload',
  'llama_model_default_params',
  'llama_model_load_from_file',
  'llama_model_free',
  'llama_model_desc',
  'llama_model_n_ctx_train',
  'llama_model_n_layer',
  'llama_model_get_vocab',
  'llama_model_chat_template',
  'llama_context_default_params',
  'llama_init_from_model',
  'llama_free',
  'llama_n_ctx',
  'llama_n_batch',
  'llama_get_memory',
  'llama_memory_clear',
  'llama_chat_apply_template',
  'llama_tokenize',
  'llama_token_to_piece',
  'llama_vocab_is_eog',
  'llama_batch_get_one',
  'llama_decode',
  'llama_sampler_chain_default_params',
  'llama_sampler_chain_init',
  'llama_sampler_chain_add',
  'llama_sampler_init_greedy',
  'llama_sampler_init_top_k',
  'llama_sampler_init_top_p',
  'llama_sampler_init_temp',
  'llama_sampler_init_dist',
  'llama_sampler_sample',
  'llama_sampler_free',
};

/// The ggml entry points: backend loading, the device list and the version.
/// They live in the ggml libraries beside llama's, or inside llama's own
/// binary on Apple, so they are looked up at run time rather than bound to
/// an asset.
const _ggmlFunctions = {
  'ggml_version',
  'ggml_commit',
  'ggml_backend_load',
  'ggml_backend_load_all_from_path',
  'ggml_backend_reg_count',
  'ggml_backend_dev_count',
  'ggml_backend_dev_get',
  'ggml_backend_dev_name',
  'ggml_backend_dev_description',
  'ggml_backend_dev_type',
};

/// Purpose: Generate both binding files.
/// Inputs: [args], optionally the libclang path.
/// Returns: None.
/// Side effects: Writes the two generated files.
/// Notes: None.
Future<void> main(List<String> args) async {
  final root = Platform.script.resolve('../');
  final include = root.resolve('third_party/llama.cpp/include/');
  final libclang = args.isNotEmpty ? args.first : _visualStudioLibclang();
  const preamble =
      '// Generated by tool/ffigen.dart from the vendored llama.cpp\n'
      '// headers (third_party/llama.cpp). Do not edit by hand.\n'
      '// ignore_for_file: type=lint';

  Input input(String header) => Input(
    entryPoints: [include.resolve(header)],
    compilerOptions: ['-I${include.toFilePath()}'],
  );

  await FfiGenerator(
    input: input('llama.h'),
    output: Output(
      dart: DartOutput(path: root.resolve('lib/src/llama_bindings.g.dart')),
      preamble: preamble,
      style: const NativeExternalBindings(
        assetId: 'package:myapps_ai_llm_llama/llama',
      ),
    ),
    visitors: [
      Visitor(
        func: (f) => f.isIncluded = _llamaFunctions.contains(f.name),
        // Passed by pointer, so it would otherwise be opaque; the backend
        // fills its fields.
        struct: (s) {
          if (s.name == 'llama_chat_message') s.isIncluded = true;
        },
      ),
    ],
  ).generate(libclangDylib: libclang == null ? null : Uri.file(libclang));

  await FfiGenerator(
    input: input('ggml-backend.h'),
    output: Output(
      dart: DartOutput(path: root.resolve('lib/src/ggml_bindings.g.dart')),
      preamble: preamble,
      style: const DynamicLibraryBindings(
        wrapperName: 'GgmlBindings',
        wrapperDocComment:
            'The ggml functions the backend calls, looked up in '
            'whichever loaded library exports them.',
      ),
    ),
    visitors: [
      Visitor(func: (f) => f.isIncluded = _ggmlFunctions.contains(f.name)),
    ],
  ).generate(libclangDylib: libclang == null ? null : Uri.file(libclang));
}

/// Purpose: Find libclang in Visual Studio's LLVM component.
/// Inputs: None.
/// Returns: Its path, or null to let ffigen search its default places.
/// Side effects: Runs `vswhere` on Windows.
/// Notes: The component matches the host: ARM64 on an ARM64 machine.
String? _visualStudioLibclang() {
  if (!Platform.isWindows) return null;
  final vswhere =
      '${Platform.environment['ProgramFiles(x86)']}\\Microsoft Visual Studio\\Installer\\vswhere.exe';
  if (!File(vswhere).existsSync()) return null;
  final result = Process.runSync(vswhere, [
    '-latest',
    '-property',
    'installationPath',
  ]);
  final vs = '${result.stdout}'.trim();
  final arch = Abi.current() == Abi.windowsArm64 ? 'ARM64' : 'x64';
  final dll = '$vs\\VC\\Tools\\Llvm\\$arch\\bin\\libclang.dll';
  return File(dll).existsSync() ? dll : null;
}
